USE [master]
GO
/****** Object:  Database [OnionArchitectureDb]    Script Date: 3/20/2020 10:26:42 PM ******/
CREATE DATABASE [OnionArchitectureDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OnionArchitectureDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\OnionArchitectureDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OnionArchitectureDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\OnionArchitectureDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [OnionArchitectureDb] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OnionArchitectureDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OnionArchitectureDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OnionArchitectureDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OnionArchitectureDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [OnionArchitectureDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OnionArchitectureDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [OnionArchitectureDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET RECOVERY FULL 
GO
ALTER DATABASE [OnionArchitectureDb] SET  MULTI_USER 
GO
ALTER DATABASE [OnionArchitectureDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OnionArchitectureDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OnionArchitectureDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OnionArchitectureDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OnionArchitectureDb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'OnionArchitectureDb', N'ON'
GO
ALTER DATABASE [OnionArchitectureDb] SET QUERY_STORE = OFF
GO
USE [OnionArchitectureDb]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [OnionArchitectureDb]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 3/20/2020 10:26:42 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CustomLogs]    Script Date: 3/20/2020 10:26:43 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CustomLogs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](50) NULL,
	[Description] [nvarchar](500) NULL,
	[LogType] [nvarchar](50) NULL,
	[Message1] [nvarchar](max) NULL,
	[Message2] [nvarchar](500) NULL,
	[Message3] [nvarchar](500) NULL,
	[Message4] [nvarchar](500) NULL,
	[Message5] [nvarchar](500) NULL,
	[IsDeleted] [bit] NULL,
	[CreatedTime] [datetime] NULL,
	[CreatedName] [nvarchar](50) NULL,
	[EditedTime] [datetime] NULL,
	[EditedName] [nvarchar](50) NULL,
 CONSTRAINT [PK_CustomLogs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [OnionArchitectureDb] SET  READ_WRITE 
GO
